package play

import (
   "154.pages.dev/encoding/protobuf"
   "bytes"
   "io"
   "net/http"
   "net/http/httputil"
   "net/url"
   "os"
)

func (c checkin) upload() error {
   req := new(http.Request)
   req.Header = make(http.Header)
   req.Header["Accept-Language"] = []string{"en-GB"}
   req.Header["Authorization"] = []string{"Bearer"}
   req.Header["Host"] = []string{"android.clients.google.com"}
   req.Header["User-Agent"] = []string{"Android-Finsky/15.8.23-all [0] [PR] 259261889 (api=3,versionCode=81582300,sdk=28,device=sargo,hardware=sargo,product=sargo,platformVersionRelease=9,model=Pixel 3a,buildId=PQ3B.190705.003,isWideScreen=0,supportedAbis=arm64-v8a;armeabi-v7a;armeabi)"}
   req.Header["X-Ad-Id"] = []string{"LawadaMera"}
   req.Header["X-Dfe-Client-Id"] = []string{"am-android-google"}
   req.Header["X-Dfe-Content-Filters"] = []string{""}
   //req.Header["X-Dfe-Device-Checkin-Consistency-Token"] = []string{"ABFEt1WnR20Eg_6baiIK6y1fzRMEEzRoE-16eaUI2XMN537Wqcii9WCOSAb4wVAYpgV2QqchXRPHzlqnpyVZ3a77fD1UQw0QdXtvWbxKb2g2aKhxwzyUVqDj0BgHIvcYo2GYEx1gdpTpHkJsOo2feQJO3JCZfd6rvCmyvpeeNp2VxVc78D2mYBxz2MUTWZjZeKe_kHkeWJoyaG6WpIb6jgasPQH1C3YtvgX4WfaH78mALP2Fat8Hr9L9RxzIzE0OBhFgsD_gNW-jTjR08z_Z0id9FZX47RQuM-u44304cM-WqIHPDL1_bE8"}
   //req.Header["X-Dfe-Encoded-Targets"] = []string{"CAESN/qigQYC2AMBFfUbyA7SM5Ij/CvfBoIDgxHqGP8R3xzIBvoQtBKFDZ4HAY4FrwSVMasHBO0O2Q8akgYRAQECAQO7AQEpKZ0CnwECAwRrAQYBr9PPAoK7sQMBAQMCBAkIDAgBAwEDBAICBAUZEgMEBAMLAQEBBQEBAcYBARYED+cBfS8CHQEKkAEMMxcBIQoUDwYHIjd3DQ4MFk0JWGYZEREYAQOLAYEBFDMIEYMBAgICAgICOxkCD18LGQKEAcgDBIQBAgGLARkYCy8oBTJlBCUocxQn0QUBDkkGxgNZQq0BZSbeAmIDgAEBOgGtAaMCDAOQAZ4BBIEBKUtQUYYBQscDDxPSARA1oAEHAWmnAsMB2wFyywGLAxol+wImlwOOA80CtwN26A0WjwJVbQEJPAH+BRDeAfkHK/ABASEBCSAaHQemAzkaRiu2Ad8BdXeiAwEBGBUBBN4LEIABK4gB2AFLfwECAdoENq0CkQGMBsIBiQEtiwGgA1zyAUQ4uwS8AwhsvgPyAcEDF27vApsBHaICGhl3GSKxAR8MC6cBAgItmQYG9QIeywLvAeYBDArLAh8HASI4ELICDVmVBgsY/gHWARtcAsMBpALiAdsBA7QBpAJmIArpByn0AyAKBwHTARIHAX8D+AMBcRIBBbEDmwUBMacCHAciNp0BAQF0OgQLJDuSAh54kwFSP0eeAQQ4M5EBQgMEmwFXywFo0gFyWwMcapQBBugBPUW2AVgBKmy3AR6PAbMBGQxrUJECvQR+8gFoWDsYgQNwRSczBRXQAgtRswEW0ALMAREYAUEBIG6yATYCRE8OxgER8gMBvQEDRkwLc8MBTwHZAUOnAXiiBakDIbYBNNcCIUmuArIBSakBrgFHKs0EgwV/G3AD0wE6LgECtQJ4xQFwFbUCjQPkBS6vAQqEAUZF3QIM9wEhCoYCQhXsBCyZArQDugIziALWAdIBlQHwBdUErQE6qQaSA4EEIvYBHir9AQVLmgMCApsCKAwHuwgrENsBAjNYswEVmgIt7QJnN4wDEnta+wGfAcUBxgEtEFXQAQWdAUAeBcwBAQM7rAEJATJ0LENrdh73A6UBhAE+qwEeASxLZUMhDREuH0CGARbd7K0GlQo"}
   //req.Header["X-Dfe-Phenotype"] = []string{"H4sIAAAAAAAAAB3OO3KjMAAA0KRNuWXukBkBQkAJ2MhgAZb5u2GCwQZbCH_EJ77QHmgvtDtbv-Z9_H63zXXU0NVPB1odlyGy7751Q3CitlPDvFd8lxhz3tpNmz7P92CFw73zdHU2Ie0Ad2kmR8lxhiErTFLt3RPGfJQHSDy7Clw10bg8kqf2owLokN4SecJTLoSwBnzQSd652_MOf2d1vKBNVedzg4ciPoLz2mQ8efGAgYeLou-l-PXn_7Sna1MfhHuySxt-4esulEDp8Sbq54CPPKjpANW-lkU2IZ0F92LBI-ukCKSptqeq1eXU96LD9nZfhKHdtjSWwJqUm_2r6pMHOxk01saVanmNopjX3YxQafC4iC6T55aRbC8nTI98AF_kItIQAJb5EQxnKTO7TZDWnr01HVPxelb9A2OWX6poidMWl16K54kcu_jhXw-JSBQkVcD_fPsLSZu6joIBAAA"}
   req.Header["X-Dfe-Device-Id"] = []string{"31e6cfcf2d498dc5"}
   req.Header["X-Dfe-Mccmnc"] = []string{"20815"}
   req.Header["X-Dfe-Network-Type"] = []string{"4"}
   req.Header["X-Dfe-Request-Params"] = []string{"timeoutMs=4000"}
   req.Header["X-Dfe-Userlanguages"] = []string{"en_GB"}
   req.Header["X-Limit-Ad-Tracking-Enabled"] = []string{"false"}
   req.Method = "POST"
   req.ProtoMajor = 1
   req.ProtoMinor = 1
   req.URL = new(url.URL)
   req.URL.Host = "android.clients.google.com"
   req.URL.Path = "/fdfe/uploadDeviceConfig"
   req.URL.Scheme = "https"
   req.Body = io.NopCloser(bytes.NewReader(upload_body.Append(nil)))
   res, err := http.DefaultClient.Do(req)
   if err != nil {
      return err
   }
   defer res.Body.Close()
   if res.StatusCode != http.StatusOK {
      return errors.New(res.Status)
   }
   return nil
}

var upload_body = protobuf.Message{
   protobuf.Field{Number: 1, Type: 2, Value: protobuf.Prefix{
      protobuf.Field{Number: 1, Type: 0, Value: protobuf.Varint(3)},
      protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(1)},
      protobuf.Field{Number: 3, Type: 0, Value: protobuf.Varint(1)},
      protobuf.Field{Number: 4, Type: 0, Value: protobuf.Varint(2)},
      protobuf.Field{Number: 5, Type: 0, Value: protobuf.Varint(0)},
      protobuf.Field{Number: 6, Type: 0, Value: protobuf.Varint(0)},
      protobuf.Field{Number: 7, Type: 0, Value: protobuf.Varint(490)},
      protobuf.Field{Number: 8, Type: 0, Value: protobuf.Varint(196610)},
      protobuf.Field{Number: 9, Type: 2, Value: protobuf.Bytes("android.ext.services")},
      protobuf.Field{Number: 9, Type: 2, Value: protobuf.Bytes("android.ext.shared")},
      protobuf.Field{Number: 9, Type: 2, Value: protobuf.Bytes("android.test.base")},
      protobuf.Field{Number: 9, Type: 2, Value: protobuf.Bytes("android.test.mock")},
      protobuf.Field{Number: 9, Type: 2, Value: protobuf.Bytes("android.test.runner")},
      protobuf.Field{Number: 9, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 12, Type: 1, Value: protobuf.Fixed64(8371739161332442222)},
         protobuf.Field{Number: 12, Type: 5, Value: protobuf.Fixed32(1915647091)},
         protobuf.Field{Number: 14, Type: 5, Value: protobuf.Fixed32(1919250030)},
      }},
      protobuf.Field{Number: 9, Type: 2, Value: protobuf.Bytes("com.android.future.usb.accessory")},
      protobuf.Field{Number: 9, Type: 2, Value: protobuf.Bytes("com.android.ims.rcsmanager")},
      protobuf.Field{Number: 9, Type: 2, Value: protobuf.Bytes("com.android.location.provider")},
      protobuf.Field{Number: 9, Type: 2, Value: protobuf.Bytes("com.android.media.remotedisplay")},
      protobuf.Field{Number: 9, Type: 2, Value: protobuf.Bytes("com.android.mediadrm.signer")},
      protobuf.Field{Number: 9, Type: 2, Value: protobuf.Bytes("com.google.android.camera.experimental2018")},
      protobuf.Field{Number: 9, Type: 2, Value: protobuf.Bytes("com.google.android.dialer.support")},
      protobuf.Field{Number: 9, Type: 2, Value: protobuf.Bytes("com.google.android.gms")},
      protobuf.Field{Number: 9, Type: 2, Value: protobuf.Bytes("com.google.android.hardwareinfo")},
      protobuf.Field{Number: 9, Type: 2, Value: protobuf.Bytes("com.google.android.lowpowermonitordevicefactory")},
      protobuf.Field{Number: 9, Type: 2, Value: protobuf.Bytes("com.google.android.lowpowermonitordeviceinterface")},
      protobuf.Field{Number: 9, Type: 2, Value: protobuf.Bytes("com.google.android.maps")},
      protobuf.Field{Number: 9, Type: 2, Value: protobuf.Bytes("com.google.android.poweranomalydatafactory")},
      protobuf.Field{Number: 9, Type: 2, Value: protobuf.Bytes("com.google.android.poweranomalydatamodeminterface")},
      protobuf.Field{Number: 9, Type: 2, Value: protobuf.Bytes("com.qti.snapdragon.sdk.display")},
      protobuf.Field{Number: 9, Type: 2, Value: protobuf.Bytes("com.qualcomm.embmslibrary")},
      protobuf.Field{Number: 9, Type: 2, Value: protobuf.Bytes("com.qualcomm.qcrilhook")},
      protobuf.Field{Number: 9, Type: 2, Value: protobuf.Bytes("com.qualcomm.qti.QtiTelephonyServicelibrary")},
      protobuf.Field{Number: 9, Type: 2, Value: protobuf.Bytes("com.qualcomm.qti.imscmservice@1.0-java")},
      protobuf.Field{Number: 9, Type: 2, Value: protobuf.Bytes("com.qualcomm.qti.lpa.uimlpalibrary")},
      protobuf.Field{Number: 9, Type: 2, Value: protobuf.Bytes("com.qualcomm.qti.ltedirectdiscoverylibrary")},
      protobuf.Field{Number: 9, Type: 2, Value: protobuf.Bytes("com.qualcomm.qti.remoteSimlock.uimremotesimlocklibrary")},
      protobuf.Field{Number: 9, Type: 2, Value: protobuf.Bytes("com.qualcomm.qti.uim.uimservicelibrary")},
      protobuf.Field{Number: 9, Type: 2, Value: protobuf.Bytes("com.quicinc.cne")},
      protobuf.Field{Number: 9, Type: 2, Value: protobuf.Bytes("com.quicinc.cneapiclient")},
      protobuf.Field{Number: 9, Type: 2, Value: protobuf.Bytes("com.verizon.embms")},
      protobuf.Field{Number: 9, Type: 2, Value: protobuf.Bytes("com.verizon.provider")},
      protobuf.Field{Number: 9, Type: 2, Value: protobuf.Bytes("com.vzw.apnlib")},
      protobuf.Field{Number: 9, Type: 2, Value: protobuf.Bytes("javax.obex")},
      protobuf.Field{Number: 9, Type: 2, Value: protobuf.Bytes("org.apache.http.legacy")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.hardware.audio.low_latency")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.hardware.audio.output")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.hardware.audio.pro")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.hardware.bluetooth")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.hardware.bluetooth_le")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.hardware.camera")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.hardware.camera.any")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 12, Type: 1, Value: protobuf.Fixed64(7507048032877306990)},
         protobuf.Field{Number: 12, Type: 1, Value: protobuf.Fixed64(7146761200619447410)},
         protobuf.Field{Number: 12, Type: 1, Value: protobuf.Fixed64(8750037977858729325)},
      }},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.hardware.camera.autofocus")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.hardware.camera.capability.manual_post_processing")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.hardware.camera.capability.manual_sensor")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.hardware.camera.capability.raw")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.hardware.camera.flash")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.hardware.camera.front")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.hardware.camera.level.full")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.hardware.faketouch")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.hardware.fingerprint")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.hardware.location")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.hardware.location.gps")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.hardware.location.network")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.hardware.microphone")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 12, Type: 1, Value: protobuf.Fixed64(7507048032877306990)},
         protobuf.Field{Number: 12, Type: 1, Value: protobuf.Fixed64(7867337140998726770)},
         protobuf.Field{Number: 13, Type: 1, Value: protobuf.Fixed64(7308901739622527587)},
      }},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.hardware.nfc")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.hardware.nfc.any")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.hardware.nfc.hce")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.hardware.nfc.hcef")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.hardware.opengles.aep")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.hardware.ram.normal")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 12, Type: 1, Value: protobuf.Fixed64(7507048032877306990)},
         protobuf.Field{Number: 12, Type: 1, Value: protobuf.Fixed64(8227625111188366450)},
         protobuf.Field{Number: 12, Type: 1, Value: protobuf.Fixed64(7809643567100341869)},
      }},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.hardware.screen.landscape")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.hardware.screen.portrait")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.hardware.sensor.accelerometer")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.hardware.sensor.assist")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.hardware.sensor.barometer")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.hardware.sensor.compass")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.hardware.sensor.gyroscope")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.hardware.sensor.hifi_sensors")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.hardware.sensor.light")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.hardware.sensor.proximity")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.hardware.sensor.stepcounter")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.hardware.sensor.stepdetector")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.hardware.strongbox_keystore")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.hardware.telephony")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.hardware.telephony.carrierlock")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.hardware.telephony.cdma")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.hardware.telephony.euicc")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.hardware.telephony.gsm")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.hardware.touchscreen")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.hardware.touchscreen.multitouch")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.hardware.touchscreen.multitouch.distinct")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.hardware.touchscreen.multitouch.jazzhand")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.hardware.usb.accessory")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.hardware.usb.host")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.hardware.vulkan.compute")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.hardware.vulkan.level")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.hardware.vulkan.version")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.hardware.wifi")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.hardware.wifi.aware")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 12, Type: 1, Value: protobuf.Fixed64(7507048032877306990)},
         protobuf.Field{Number: 12, Type: 1, Value: protobuf.Fixed64(8587913081378006130)},
         protobuf.Field{Number: 13, Type: 1, Value: protobuf.Fixed64(7310012310535170406)},
      }},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.hardware.wifi.direct")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.hardware.wifi.passpoint")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.hardware.wifi.rtt")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.software.activities_on_secondary_displays")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.software.app_widgets")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.software.autofill")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.software.backup")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.software.cant_save_state")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.software.companion_device_setup")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.software.connectionservice")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.software.cts")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.software.device_admin")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.software.device_id_attestation")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.software.file_based_encryption")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.software.home_screen")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.software.input_methods")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.software.live_wallpaper")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.software.managed_users")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.software.midi")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.software.picture_in_picture")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.software.print")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.software.securely_removes_users")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.software.sip")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.software.sip.voip")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.software.verified_boot")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.software.voice_recognizers")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.software.webview")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("com.google.android.apps.dialer.SUPPORTED")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("com.google.android.apps.photos.PIXEL_2019_MIDYEAR_PRELOAD")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("com.google.android.feature.EXCHANGE_6_2")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("com.google.android.feature.GOOGLE_BUILD")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("com.google.android.feature.GOOGLE_EXPERIENCE")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("com.google.android.feature.PIXEL_2017_EXPERIENCE")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("com.google.android.feature.PIXEL_2018_EXPERIENCE")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("com.google.android.feature.PIXEL_2019_MIDYEAR_EXPERIENCE")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("com.google.android.feature.PIXEL_EXPERIENCE")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("com.google.android.feature.TURBO_PRELOAD")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("com.google.android.feature.WELLBEING")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("com.google.android.feature.ZERO_TOUCH")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("com.google.hardware.camera.easel_2018")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("com.verizon.hardware.telephony.ehrpd")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("com.verizon.hardware.telephony.lte")},
      protobuf.Field{Number: 11, Type: 2, Value: protobuf.Bytes("arm64-v8a")},
      protobuf.Field{Number: 11, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 12, Type: 1, Value: protobuf.Fixed64(7005479156896394610)},
      }},
      protobuf.Field{Number: 11, Type: 2, Value: protobuf.Bytes("armeabi-v7a")},
      protobuf.Field{Number: 11, Type: 2, Value: protobuf.Bytes("armeabi")},
      protobuf.Field{Number: 12, Type: 0, Value: protobuf.Varint(1080)},
      protobuf.Field{Number: 13, Type: 0, Value: protobuf.Varint(2073)},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("af")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("af_ZA")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("am")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("am_ET")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("ar")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("ar_EG")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("ar_SA")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("ar_XB")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("as")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("ast")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("az")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("be")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("be_BY")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("bg")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("bg_BG")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("bh_IN")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("bn")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("bs")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("ca")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("ca_ES")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("cs")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("cs_CZ")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("cy_GB")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("da")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("da_DK")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("de")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("de_DE")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("el")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("el_GR")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 12, Type: 5, Value: protobuf.Fixed32(1380409196)},
      }},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("en")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("en_AU")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 12, Type: 5, Value: protobuf.Fixed32(1430347630)},
      }},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("en_CA")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 12, Type: 5, Value: protobuf.Fixed32(1094934382)},
      }},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("en_GB")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 12, Type: 5, Value: protobuf.Fixed32(1111973742)},
      }},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("en_IN")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 12, Type: 5, Value: protobuf.Fixed32(1313431406)},
      }},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("en_US")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 12, Type: 5, Value: protobuf.Fixed32(1398103918)},
      }},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("en_XA")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 12, Type: 5, Value: protobuf.Fixed32(1096310638)},
      }},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("es")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("es_ES")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 12, Type: 5, Value: protobuf.Fixed32(1397055347)},
      }},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("es_US")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 12, Type: 5, Value: protobuf.Fixed32(1398103923)},
      }},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("et")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("et_EE")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 12, Type: 5, Value: protobuf.Fixed32(1162174324)},
      }},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("eu")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("fa")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("fa_IR")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("fi")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("fi_FI")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("fil")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("fil_PH")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("fr")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("fr_CA")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("fr_FR")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("gl")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("gl_ES")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("gu")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("hi")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 13, Type: 0, Value: protobuf.Varint(105)},
      }},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("hi_IN")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("hr")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 13, Type: 0, Value: protobuf.Varint(114)},
      }},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("hr_HR")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("hu")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 13, Type: 0, Value: protobuf.Varint(117)},
      }},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("hu_HU")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("hy")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 13, Type: 0, Value: protobuf.Varint(121)},
      }},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("in")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("in_ID")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("is")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("it")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("it_IT")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("iw")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("iw_IL")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("ja")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("ja_JP")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("ka")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("kab_DZ")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("kk")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("km")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("kn")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("ko")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("ko_KR")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("ky")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("lo")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("lt")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("lt_LT")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("lv")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("lv_LV")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("mk")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("ml")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("mn")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("mr")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("ms")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("ms_MY")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 13, Type: 5, Value: protobuf.Fixed32(1498242931)},
      }},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("my")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("nb")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("nb_NO")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("ne")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("nl")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("nl_NL")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("or")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("pa")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 14, Type: 0, Value: protobuf.Varint(97)},
      }},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("pa_IN")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("pl")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 14, Type: 0, Value: protobuf.Varint(108)},
      }},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("pl_PL")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("pt")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 14, Type: 0, Value: protobuf.Varint(116)},
      }},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("pt_BR")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("pt_PT")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("ro")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("ro_RO")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("ru")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("ru_RU")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("sc_IT")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("si")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("sk")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("sk_SK")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("sl")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("sl_SI")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("sq")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("sr")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("sr_Latn")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("sr_RS")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("sv")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("sv_SE")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("sw")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("sw_TZ")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("ta")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("te")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("th")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("th_TH")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("tr")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("tr_TR")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("uk")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("uk_UA")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 14, Type: 5, Value: protobuf.Fixed32(1096114027)},
      }},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("ur")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("uz")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("vi")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("vi_VN")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("zh_CN")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("zh_HK")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("zh_TW")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("zu")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("zu_ZA")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_AMD_compressed_ATC_texture")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_AMD_performance_monitor")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_ANDROID_extension_pack_es31a")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_APPLE_texture_2D_limited_npot")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_ARB_vertex_buffer_object")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_ARM_shader_framebuffer_fetch_depth_stencil")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_EXT_EGL_image_array")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_EXT_EGL_image_external_wrap_modes")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_EXT_EGL_image_storage")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_EXT_YUV_target")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_EXT_blend_func_extended")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_EXT_blit_framebuffer_params")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_EXT_buffer_storage")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_EXT_clip_control")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_EXT_clip_cull_distance")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_EXT_color_buffer_float")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_EXT_color_buffer_half_float")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_EXT_copy_image")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_EXT_debug_label")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_EXT_debug_marker")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_EXT_discard_framebuffer")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_EXT_disjoint_timer_query")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_EXT_draw_buffers_indexed")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_EXT_external_buffer")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_EXT_geometry_shader")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_EXT_gpu_shader5")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_EXT_memory_object")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_EXT_memory_object_fd")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_EXT_multisampled_render_to_texture")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_EXT_multisampled_render_to_texture2")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_EXT_primitive_bounding_box")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_EXT_protected_textures")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_EXT_robustness")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_EXT_sRGB")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_EXT_sRGB_write_control")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_EXT_shader_framebuffer_fetch")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_EXT_shader_io_blocks")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_EXT_shader_non_constant_global_initializers")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_EXT_tessellation_shader")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_EXT_texture_border_clamp")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_EXT_texture_buffer")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_EXT_texture_cube_map_array")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_EXT_texture_filter_anisotropic")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_EXT_texture_format_BGRA8888")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_EXT_texture_format_sRGB_override")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_EXT_texture_norm16")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_EXT_texture_sRGB_R8")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_EXT_texture_sRGB_decode")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_EXT_texture_type_2_10_10_10_REV")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_KHR_blend_equation_advanced")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_KHR_blend_equation_advanced_coherent")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_KHR_debug")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_KHR_no_error")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_KHR_robust_buffer_access_behavior")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_KHR_texture_compression_astc_hdr")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_KHR_texture_compression_astc_ldr")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_NV_shader_noperspective_interpolation")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OES_EGL_image")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OES_EGL_image_external")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OES_EGL_image_external_essl3")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OES_EGL_sync")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OES_blend_equation_separate")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OES_blend_func_separate")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OES_blend_subtract")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OES_compressed_ETC1_RGB8_texture")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OES_compressed_paletted_texture")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OES_depth24")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OES_depth_texture")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OES_depth_texture_cube_map")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OES_draw_texture")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OES_element_index_uint")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OES_framebuffer_object")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OES_get_program_binary")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OES_matrix_palette")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OES_packed_depth_stencil")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OES_point_size_array")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OES_point_sprite")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OES_read_format")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OES_rgb8_rgba8")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OES_sample_shading")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OES_sample_variables")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OES_shader_image_atomic")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OES_shader_multisample_interpolation")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OES_standard_derivatives")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OES_stencil_wrap")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OES_surfaceless_context")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OES_texture_3D")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OES_texture_compression_astc")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OES_texture_cube_map")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OES_texture_env_crossbar")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OES_texture_float")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OES_texture_float_linear")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OES_texture_half_float")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OES_texture_half_float_linear")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OES_texture_mirrored_repeat")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OES_texture_npot")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OES_texture_stencil8")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OES_texture_storage_multisample_2d_array")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OES_vertex_array_object")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OES_vertex_half_float")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OVR_multiview")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OVR_multiview2")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OVR_multiview_multisampled_render_to_texture")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_QCOM_alpha_test")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_QCOM_extended_get")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_QCOM_shader_framebuffer_fetch_noncoherent")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_QCOM_texture_foveated")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_QCOM_tiled_rendering")},
      protobuf.Field{Number: 16, Type: 0, Value: protobuf.Varint(0)},
      protobuf.Field{Number: 19, Type: 0, Value: protobuf.Varint(0)},
      protobuf.Field{Number: 20, Type: 0, Value: protobuf.Varint(8589935000)},
      protobuf.Field{Number: 21, Type: 0, Value: protobuf.Varint(8)},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n\"android.hardware.audio.low_latency\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.hardware.audio.low_latency")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n\x1dandroid.hardware.audio.output\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.hardware.audio.output")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n\x1aandroid.hardware.audio.pro\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.hardware.audio.pro")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n\x1aandroid.hardware.bluetooth\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.hardware.bluetooth")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n\x1dandroid.hardware.bluetooth_le\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.hardware.bluetooth_le")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n\x17android.hardware.camera\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.hardware.camera")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n\x1bandroid.hardware.camera.any\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.hardware.camera.any")},
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Maybe{
            protobuf.Field{Number: 12, Type: 1, Value: protobuf.Fixed64(7507048032877306990)},
            protobuf.Field{Number: 12, Type: 1, Value: protobuf.Fixed64(7146761200619447410)},
            protobuf.Field{Number: 12, Type: 1, Value: protobuf.Fixed64(8750037977858729325)},
         }},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n!android.hardware.camera.autofocus\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.hardware.camera.autofocus")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n9android.hardware.camera.capability.manual_post_processing\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.hardware.camera.capability.manual_post_processing")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n0android.hardware.camera.capability.manual_sensor\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.hardware.camera.capability.manual_sensor")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n&android.hardware.camera.capability.raw\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.hardware.camera.capability.raw")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n\x1dandroid.hardware.camera.flash\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.hardware.camera.flash")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n\x1dandroid.hardware.camera.front\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.hardware.camera.front")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n\"android.hardware.camera.level.full\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.hardware.camera.level.full")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n\x1aandroid.hardware.faketouch\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.hardware.faketouch")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n\x1candroid.hardware.fingerprint\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.hardware.fingerprint")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n\x19android.hardware.location\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.hardware.location")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n\x1dandroid.hardware.location.gps\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.hardware.location.gps")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n!android.hardware.location.network\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.hardware.location.network")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n\x1bandroid.hardware.microphone\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.hardware.microphone")},
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Maybe{
            protobuf.Field{Number: 12, Type: 1, Value: protobuf.Fixed64(7507048032877306990)},
            protobuf.Field{Number: 12, Type: 1, Value: protobuf.Fixed64(7867337140998726770)},
            protobuf.Field{Number: 13, Type: 1, Value: protobuf.Fixed64(7308901739622527587)},
         }},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n\x14android.hardware.nfc\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.hardware.nfc")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n\x18android.hardware.nfc.any\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.hardware.nfc.any")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n\x18android.hardware.nfc.hce\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.hardware.nfc.hce")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n\x19android.hardware.nfc.hcef\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.hardware.nfc.hcef")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n\x1dandroid.hardware.opengles.aep\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.hardware.opengles.aep")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n\x1bandroid.hardware.ram.normal\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.hardware.ram.normal")},
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Maybe{
            protobuf.Field{Number: 12, Type: 1, Value: protobuf.Fixed64(7507048032877306990)},
            protobuf.Field{Number: 12, Type: 1, Value: protobuf.Fixed64(8227625111188366450)},
            protobuf.Field{Number: 12, Type: 1, Value: protobuf.Fixed64(7809643567100341869)},
         }},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n!android.hardware.screen.landscape\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.hardware.screen.landscape")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n android.hardware.screen.portrait\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.hardware.screen.portrait")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n%android.hardware.sensor.accelerometer\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.hardware.sensor.accelerometer")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n\x1eandroid.hardware.sensor.assist\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.hardware.sensor.assist")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n!android.hardware.sensor.barometer\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.hardware.sensor.barometer")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n\x1fandroid.hardware.sensor.compass\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.hardware.sensor.compass")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n!android.hardware.sensor.gyroscope\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.hardware.sensor.gyroscope")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n$android.hardware.sensor.hifi_sensors\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.hardware.sensor.hifi_sensors")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n\x1dandroid.hardware.sensor.light\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.hardware.sensor.light")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n!android.hardware.sensor.proximity\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.hardware.sensor.proximity")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n#android.hardware.sensor.stepcounter\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.hardware.sensor.stepcounter")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n$android.hardware.sensor.stepdetector\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.hardware.sensor.stepdetector")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n#android.hardware.strongbox_keystore\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.hardware.strongbox_keystore")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n\x1aandroid.hardware.telephony\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.hardware.telephony")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n&android.hardware.telephony.carrierlock\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.hardware.telephony.carrierlock")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n\x1fandroid.hardware.telephony.cdma\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.hardware.telephony.cdma")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n android.hardware.telephony.euicc\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.hardware.telephony.euicc")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n\x1eandroid.hardware.telephony.gsm\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.hardware.telephony.gsm")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n\x1candroid.hardware.touchscreen\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.hardware.touchscreen")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n'android.hardware.touchscreen.multitouch\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.hardware.touchscreen.multitouch")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n0android.hardware.touchscreen.multitouch.distinct\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.hardware.touchscreen.multitouch.distinct")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n0android.hardware.touchscreen.multitouch.jazzhand\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.hardware.touchscreen.multitouch.jazzhand")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n\x1eandroid.hardware.usb.accessory\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.hardware.usb.accessory")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n\x19android.hardware.usb.host\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.hardware.usb.host")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n\x1fandroid.hardware.vulkan.compute\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.hardware.vulkan.compute")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n\x1dandroid.hardware.vulkan.level\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.hardware.vulkan.level")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n\x1fandroid.hardware.vulkan.version\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.hardware.vulkan.version")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n\x15android.hardware.wifi\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.hardware.wifi")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n\x1bandroid.hardware.wifi.aware\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.hardware.wifi.aware")},
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Maybe{
            protobuf.Field{Number: 12, Type: 1, Value: protobuf.Fixed64(7507048032877306990)},
            protobuf.Field{Number: 12, Type: 1, Value: protobuf.Fixed64(8587913081378006130)},
            protobuf.Field{Number: 13, Type: 1, Value: protobuf.Fixed64(7310012310535170406)},
         }},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n\x1candroid.hardware.wifi.direct\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.hardware.wifi.direct")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n\x1fandroid.hardware.wifi.passpoint\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.hardware.wifi.passpoint")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n\x19android.hardware.wifi.rtt\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.hardware.wifi.rtt")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n1android.software.activities_on_secondary_displays\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.software.activities_on_secondary_displays")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n\x1candroid.software.app_widgets\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.software.app_widgets")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n\x19android.software.autofill\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.software.autofill")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n\x17android.software.backup\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.software.backup")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n android.software.cant_save_state\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.software.cant_save_state")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n'android.software.companion_device_setup\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.software.companion_device_setup")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n\"android.software.connectionservice\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.software.connectionservice")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n\x14android.software.cts\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.software.cts")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n\x1dandroid.software.device_admin\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.software.device_admin")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n&android.software.device_id_attestation\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.software.device_id_attestation")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n&android.software.file_based_encryption\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.software.file_based_encryption")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n\x1candroid.software.home_screen\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.software.home_screen")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n\x1eandroid.software.input_methods\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.software.input_methods")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n\x1fandroid.software.live_wallpaper\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.software.live_wallpaper")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n\x1eandroid.software.managed_users\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.software.managed_users")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n\x15android.software.midi\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.software.midi")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n#android.software.picture_in_picture\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.software.picture_in_picture")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n\x16android.software.print\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.software.print")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n'android.software.securely_removes_users\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.software.securely_removes_users")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n\x14android.software.sip\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.software.sip")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n\x19android.software.sip.voip\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.software.sip.voip")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n\x1eandroid.software.verified_boot\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.software.verified_boot")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n\"android.software.voice_recognizers\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.software.voice_recognizers")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n\x18android.software.webview\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.software.webview")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n(com.google.android.apps.dialer.SUPPORTED\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("com.google.android.apps.dialer.SUPPORTED")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n9com.google.android.apps.photos.PIXEL_2019_MIDYEAR_PRELOAD\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("com.google.android.apps.photos.PIXEL_2019_MIDYEAR_PRELOAD")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n'com.google.android.feature.EXCHANGE_6_2\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("com.google.android.feature.EXCHANGE_6_2")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n'com.google.android.feature.GOOGLE_BUILD\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("com.google.android.feature.GOOGLE_BUILD")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n,com.google.android.feature.GOOGLE_EXPERIENCE\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("com.google.android.feature.GOOGLE_EXPERIENCE")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n0com.google.android.feature.PIXEL_2017_EXPERIENCE\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("com.google.android.feature.PIXEL_2017_EXPERIENCE")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n0com.google.android.feature.PIXEL_2018_EXPERIENCE\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("com.google.android.feature.PIXEL_2018_EXPERIENCE")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n8com.google.android.feature.PIXEL_2019_MIDYEAR_EXPERIENCE\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("com.google.android.feature.PIXEL_2019_MIDYEAR_EXPERIENCE")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n+com.google.android.feature.PIXEL_EXPERIENCE\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("com.google.android.feature.PIXEL_EXPERIENCE")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n(com.google.android.feature.TURBO_PRELOAD\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("com.google.android.feature.TURBO_PRELOAD")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n$com.google.android.feature.WELLBEING\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("com.google.android.feature.WELLBEING")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n%com.google.android.feature.ZERO_TOUCH\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("com.google.android.feature.ZERO_TOUCH")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n%com.google.hardware.camera.easel_2018\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("com.google.hardware.camera.easel_2018")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n$com.verizon.hardware.telephony.ehrpd\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("com.verizon.hardware.telephony.ehrpd")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Bytes("\n\"com.verizon.hardware.telephony.lte\x10\x00")},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Maybe{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("com.verizon.hardware.telephony.lte")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
   }},
}
