package play

import (
   "154.pages.dev/encoding/protobuf"
   "bytes"
   "errors"
   "io"
   "net/http"
)

func Checkin_Acquire(platform string) ([]byte, error) {
   res, err := http.Post(
      "https://android.googleapis.com/checkin", "application/x-protobuffer",
      bytes.NewReader(Phone_Acquire.Append(nil)),
   )
   if err != nil {
      return nil, err
   }
   defer res.Body.Close()
   if res.StatusCode != http.StatusOK {
      return nil, errors.New(res.Status)
   }
   return io.ReadAll(res.Body)
}

var Phone_Acquire = protobuf.Message{
   protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
   protobuf.Field{Number: 3, Type: 2, Value: protobuf.Bytes("1-da39a3ee5e6b4b0d3255bfef95601890afd80709")},
   protobuf.Field{Number: 4, Type: 2, Value: protobuf.Prefix{
      protobuf.Field{Number: 1, Type: 2, Value: protobuf.Prefix{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("generic_x86/sdk_google_phone_x86/generic_x86:5.0.2/LSY66K/6695550:eng/test-keys")},
         protobuf.Field{Number: 2, Type: 2, Value: protobuf.Bytes("ranchu")},
         protobuf.Field{Number: 3, Type: 2, Value: protobuf.Bytes("generic_x86")},
         protobuf.Field{Number: 5, Type: 2, Value: protobuf.Bytes("unknown")},
         protobuf.Field{Number: 6, Type: 2, Value: protobuf.Bytes("android-google")},
         protobuf.Field{Number: 7, Type: 0, Value: protobuf.Varint(1595298807)},
         protobuf.Field{Number: 8, Type: 0, Value: protobuf.Varint(202414013)},
         protobuf.Field{Number: 9, Type: 2, Value: protobuf.Bytes("generic_x86")},
         protobuf.Field{Number: 10, Type: 0, Value: protobuf.Varint(21)},
         protobuf.Field{Number: 11, Type: 2, Value: protobuf.Bytes("Android SDK built for x86")},
         protobuf.Field{Number: 12, Type: 2, Value: protobuf.Bytes("unknown")},
         protobuf.Field{Number: 13, Type: 2, Value: protobuf.Bytes("sdk_google_phone_x86")},
         protobuf.Field{Number: 14, Type: 0, Value: protobuf.Varint(0)},
         protobuf.Field{Number: 15, Type: 2, Value: protobuf.Prefix{
            protobuf.Field{Number: 1, Type: 0, Value: protobuf.Varint(1)},
            protobuf.Field{Number: 2, Type: 2, Value: protobuf.Bytes("android-google")},
         }},
      }},
      protobuf.Field{Number: 6, Type: 2, Value: protobuf.Bytes("310260")},
      protobuf.Field{Number: 7, Type: 2, Value: protobuf.Bytes("310260")},
      protobuf.Field{Number: 8, Type: 2, Value: protobuf.Bytes("MOBILE:LTE:")},
      protobuf.Field{Number: 9, Type: 0, Value: protobuf.Varint(0)},
      protobuf.Field{Number: 14, Type: 0, Value: protobuf.Varint(2)},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Prefix{
         protobuf.Field{Number: 1, Type: 0, Value: protobuf.Varint(1)},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(1)},
         protobuf.Field{Number: 3, Type: 2, Value: protobuf.Bytes("unspecified")},
         protobuf.Field{Number: 4, Type: 2, Value: protobuf.Bytes("")},
         protobuf.Field{Number: 5, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 16, Type: 2, Value: protobuf.Prefix{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("310260")},
         protobuf.Field{Number: 2, Type: 2, Value: protobuf.Bytes("Android")},
         protobuf.Field{Number: 3, Type: 2, Value: protobuf.Bytes("0")},
         protobuf.Field{Number: 4, Type: 0, Value: protobuf.Varint(0)},
         protobuf.Field{Number: 4, Type: 0, Value: protobuf.Varint(1)},
         protobuf.Field{Number: 4, Type: 0, Value: protobuf.Varint(2)},
         protobuf.Field{Number: 6, Type: 2, Value: protobuf.Bytes("310260000000000")},
         protobuf.Field{Number: 8, Type: 2, Value: protobuf.Bytes("\x17L")},
      }},
      protobuf.Field{Number: 19, Type: 2, Value: protobuf.Bytes("MOBILE")},
   }},
   protobuf.Field{Number: 6, Type: 2, Value: protobuf.Bytes("en-US")},
   protobuf.Field{Number: 7, Type: 0, Value: protobuf.Varint(16045423075696072033)},
   protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("358240051111110")},
   protobuf.Field{Number: 11, Type: 2, Value: protobuf.Bytes("")},
   protobuf.Field{Number: 12, Type: 2, Value: protobuf.Bytes("America/Denver")},
   protobuf.Field{Number: 14, Type: 0, Value: protobuf.Varint(3)},
   protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("71Q6Rn2DDZl1zPDVaaeEHItd+Yg=")},
   protobuf.Field{Number: 16, Type: 2, Value: protobuf.Bytes("EMULATOR32X1X14X0")},
   protobuf.Field{Number: 18, Type: 2, Value: protobuf.Prefix{
      protobuf.Field{Number: 1, Type: 0, Value: protobuf.Varint(3)},
      protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(1)},
      protobuf.Field{Number: 3, Type: 0, Value: protobuf.Varint(2)},
      protobuf.Field{Number: 4, Type: 0, Value: protobuf.Varint(2)},
      protobuf.Field{Number: 5, Type: 0, Value: protobuf.Varint(0)},
      protobuf.Field{Number: 6, Type: 0, Value: protobuf.Varint(1)},
      protobuf.Field{Number: 7, Type: 0, Value: protobuf.Varint(400)},
      protobuf.Field{Number: 8, Type: 0, Value: protobuf.Varint(196609)},
      protobuf.Field{Number: 9, Type: 2, Value: protobuf.Bytes("android.test.runner")},
      protobuf.Field{Number: 9, Type: 2, Value: protobuf.Bytes("com.android.future.usb.accessory")},
      protobuf.Field{Number: 9, Type: 2, Value: protobuf.Bytes("com.android.location.provider")},
      protobuf.Field{Number: 9, Type: 2, Value: protobuf.Bytes("com.android.media.remotedisplay")},
      protobuf.Field{Number: 9, Type: 2, Value: protobuf.Bytes("com.android.mediadrm.signer")},
      protobuf.Field{Number: 9, Type: 2, Value: protobuf.Bytes("com.google.android.gms")},
      protobuf.Field{Number: 9, Type: 2, Value: protobuf.Bytes("com.google.android.maps")},
      protobuf.Field{Number: 9, Type: 2, Value: protobuf.Bytes("com.google.android.media.effects")},
      protobuf.Field{Number: 9, Type: 2, Value: protobuf.Bytes("javax.obex")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.hardware.audio.output")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.hardware.bluetooth")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.hardware.camera")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.hardware.camera.any")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.hardware.camera.autofocus")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.hardware.faketouch")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.hardware.location")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.hardware.location.network")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.hardware.microphone")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.hardware.screen.landscape")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.hardware.screen.portrait")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.hardware.sensor.accelerometer")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.hardware.sensor.compass")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.hardware.touchscreen")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.hardware.touchscreen.multitouch")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.hardware.touchscreen.multitouch.distinct")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.hardware.touchscreen.multitouch.jazzhand")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.hardware.usb.accessory")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.software.app_widgets")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.software.backup")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.software.connectionservice")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.software.device_admin")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.software.home_screen")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.software.input_methods")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.software.live_wallpaper")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.software.managed_users")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.software.print")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.software.voice_recognizers")},
      protobuf.Field{Number: 10, Type: 2, Value: protobuf.Bytes("android.software.webview")},
      protobuf.Field{Number: 11, Type: 2, Value: protobuf.Bytes("x86")},
      protobuf.Field{Number: 12, Type: 0, Value: protobuf.Varint(1080)},
      protobuf.Field{Number: 13, Type: 0, Value: protobuf.Varint(2160)},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("af")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("am")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("ar")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("ar-EG")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("ar-IL")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("as")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("az")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("be")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("bg")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("bg-BG")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("bn")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("bs")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("ca")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("ca-ES")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("cs")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("cs-CZ")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("da")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("da-DK")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("de")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("de-AT")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("de-CH")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("de-DE")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("de-LI")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("el")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("el-GR")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("en")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("en-AU")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("en-CA")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("en-GB")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("en-IE")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("en-IN")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("en-NZ")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("en-SG")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("en-US")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("en-ZA")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("es")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("es-ES")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("es-US")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("et")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("eu")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("fa")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("fi")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("fi-FI")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("fil")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("fil-PH")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("fr")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("fr-BE")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("fr-CA")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("fr-CH")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("fr-FR")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("gl")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("gu")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("hi")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("hi-IN")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("hr")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("hr-HR")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("hu")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("hu-HU")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("hy")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("id")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("in")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("is")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("it")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("it-CH")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("it-IT")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("iw")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("ja")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("ja-JP")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("ka")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("kk")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("km")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("kn")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("ko")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("ko-KR")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("ky")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("lo")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("lt")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("lt-LT")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("lv")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("lv-LV")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("mk")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("ml")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("mn")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("mr")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("ms")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("my")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("nb")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("nb-NO")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("ne")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("nl")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("nl-BE")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("nl-NL")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("or")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("pa")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("pl")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("pl-PL")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("pt")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("pt-BR")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("pt-PT")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("ro")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("ro-RO")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("ru")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("ru-RU")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("si")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("sk")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("sk-SK")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("sl")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("sl-SI")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("sq")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("sr")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("sr-Latn")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("sr-RS")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("sv")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("sv-SE")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("sw")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("ta")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("te")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("th")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("th-TH")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("tr")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("tr-TR")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("uk")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("uk-UA")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("ur")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("uz")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("vi")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("vi-VN")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("zh-CN")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("zh-HK")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("zh-TW")},
      protobuf.Field{Number: 14, Type: 2, Value: protobuf.Bytes("zu")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("ANDROID_EMU_CHECKSUM_HELPER_v1")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("ANDROID_EMU_dma_v1")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("ANDROID_EMU_gles_max_version_3_1")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("ANDROID_EMU_host_side_tracing")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("ANDROID_EMU_sync_buffer_data")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_APPLE_texture_format_BGRA8888")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_EXT_color_buffer_float")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_EXT_color_buffer_half_float")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_EXT_debug_marker")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_EXT_texture_format_BGRA8888")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_KHR_texture_compression_astc_ldr")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OES_EGL_image")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OES_EGL_image_external")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OES_EGL_image_external_essl3")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OES_EGL_sync")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OES_blend_equation_separate")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OES_blend_func_separate")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OES_blend_subtract")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OES_byte_coordinates")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OES_compressed_ETC1_RGB8_texture")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OES_compressed_paletted_texture")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OES_depth24")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OES_depth32")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OES_depth_texture")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OES_draw_texture")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OES_element_index_uint")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OES_fbo_render_mipmap")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OES_framebuffer_object")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OES_packed_depth_stencil")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OES_point_size_array")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OES_point_sprite")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OES_rgb8_rgba8")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OES_single_precision")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OES_stencil1")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OES_stencil4")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OES_stencil8")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OES_stencil_wrap")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OES_texture_cube_map")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OES_texture_env_crossbar")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OES_texture_float")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OES_texture_float_linear")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OES_texture_half_float")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OES_texture_half_float_linear")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OES_texture_mirored_repeat")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OES_texture_npot")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OES_vertex_array_object")},
      protobuf.Field{Number: 15, Type: 2, Value: protobuf.Bytes("GL_OES_vertex_half_float")},
      protobuf.Field{Number: 18, Type: 0, Value: protobuf.Varint(432)},
      protobuf.Field{Number: 19, Type: 0, Value: protobuf.Varint(0)},
      protobuf.Field{Number: 20, Type: 0, Value: protobuf.Varint(1588760576)},
      protobuf.Field{Number: 21, Type: 0, Value: protobuf.Varint(4)},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Prefix{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.hardware.audio.output")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Prefix{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.hardware.bluetooth")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Prefix{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.hardware.camera")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Prefix{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.hardware.camera.any")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Prefix{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.hardware.camera.autofocus")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Prefix{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.hardware.faketouch")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Prefix{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.hardware.location")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Prefix{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.hardware.location.network")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Prefix{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.hardware.microphone")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Prefix{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.hardware.screen.landscape")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Prefix{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.hardware.screen.portrait")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Prefix{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.hardware.sensor.accelerometer")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Prefix{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.hardware.sensor.compass")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Prefix{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.hardware.touchscreen")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Prefix{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.hardware.touchscreen.multitouch")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Prefix{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.hardware.touchscreen.multitouch.distinct")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Prefix{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.hardware.touchscreen.multitouch.jazzhand")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Prefix{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.hardware.usb.accessory")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Prefix{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.software.app_widgets")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Prefix{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.software.backup")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Prefix{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.software.connectionservice")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Prefix{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.software.device_admin")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Prefix{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.software.home_screen")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Prefix{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.software.input_methods")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Prefix{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.software.live_wallpaper")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Prefix{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.software.managed_users")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Prefix{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.software.print")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Prefix{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.software.voice_recognizers")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 26, Type: 2, Value: protobuf.Prefix{
         protobuf.Field{Number: 1, Type: 2, Value: protobuf.Bytes("android.software.webview")},
         protobuf.Field{Number: 2, Type: 0, Value: protobuf.Varint(0)},
      }},
      protobuf.Field{Number: 28, Type: 0, Value: protobuf.Varint(0)},
      protobuf.Field{Number: 30, Type: 0, Value: protobuf.Varint(2)},
   }},
   protobuf.Field{Number: 20, Type: 0, Value: protobuf.Varint(0)},
   protobuf.Field{Number: 22, Type: 0, Value: protobuf.Varint(0)},
   protobuf.Field{Number: 24, Type: 2, Value: protobuf.Bytes("CgZ0KIknAKbSEFsAAHdU9h5a1xWSAFpFJRNTS5M9AC4R4ZGh9VMLBADDJ63W0SEMAFD2hUYLAaNSAQ4qN5jJF3GjAf8ZjNa77UdCBSQ_vtIfIwS5A5XXI_rK0Z7tAhh65LU_Oxc62geZBgDroQgSu4KwYdlJZ_HmPwL3nTLzb7lYaT8yncrYqC9W9bzVfRtIv6vpEPOV_0RNZ51tpE00GbfYpOrwkulp_k_7r6HUpboUKnAOYyCylsR5O1w7bfV7Dr26lu4fl1kD0moo5eKHPrhLHH7W6mAR5ak6OVwW7ryEe2Zkyz4OOtvB8AdJOZilnbZ7q0drF0zs_-ItNo3dasPvo0z8QFw5nvEDortUqTL27V51JyL-8o5Vq6-UUnrOJAXYU1gi_zEq8x6OwAU4cYhlgXJJhWZu5DV-VhA-Eq0Io24VM2M68Kqt4eRj2AeeGHeAydXGv6v-SO1RyRiiWMRK904vXBDPuUyzlHVkZAZ5Bz1viqCsQa7lWMwl4Q6aH_I1UUGpVjyiIypWsSXRvS2vDCkiiSIjM-JAcJslE-cipzIeXxK9lpfLvrJ0sMVgduFtKYjgoucbMyj4DgvcmlE1o5cqYxA3QiXbpyM_6_JvG1-DPLxczrOMXS4L4T3xeW1uhSjY8dSnNuhdZ1sWAGR1h3Wcb2xwiw57Pxyt-qnNaEoX9ulW6IVteihmAcpvi5vQSMd_f2ghC364_LpRk6g-FQYgjHO6riOgnGLOkGMpexSkEiq27mJSJkRjLKEx9ra8j0ooXpZ85DYL0XnuKo7SaA4GZBQWnvEISdNiQHGY7YOb-Gm4WesiVhPSB4rTjr4kkP1G0ZN_PRWRo_YSzj_OwKs7BLj57F9W2C9ila74q45fZebl2oPZOSM-xmuHDgTotjUAVyHe7Aan2hkmUNIeUbFdjvM2Fy9nrS89xgSkU3PkzEU1x_cxUqmwvc8McMg8pHTF_ifaf9TZjxbo2AianuDB4LGwWMDZLCdFZ1-gmPslYiaYnADjs5QpRpR5qmi5Dko3fCWWEhDPVX_qWBMouNhykDbsjFPwznAtiAg06BFZpN4gFi27y-CsmbrpCzuHJHDZAU_NKPabSdmmnMr9szYgLJFN3AYWNMVU04t0v7mYxTLUa_V05wltZWDy5A-hUMNqA7tVtDjNkydqx-W3mZDALmXWCquvaKSCFmn_Vx84YdAPm-6AkfrI2o4xOGs4S5gS6v7487uErJcNmBLD3-D0qrWdjLsBEvwzOJhEHRMQYEWXLTcBg7viCn4qPkKUciigfnzlpkGtlPTyB9ry0ykoz5hVZuclnuyzf0GWMnS3I-1hsB0djnNYP36PybTw24feOh4UuU-jSzcGFi_xpxslt5044TMpzxIRbdTallL90bosYv9_YzrBfzygY9uQacbeZhVGwPCTsFse83yH7bhnrd8gfrBPO7uuC-L7mwQR3SQtJRqIWQPdO5iZDgIERQRdZ4CHYf2Y6qkF36Y73h0A7vLeLcbGXq_Rj9KE-P-xWdzOeAc_Nynt7bPwtBZUv5ViERWs3AiB8Z7t_kUaUSVDNl1RsE2WwzwPREd1mSxs2VSxUlZaQeNa-zD5xcn_UOLWiTtC1bQVi5VdRoAsA_TL5aRe2gCeWHnX8U1nR62DtglEXToJxTvSY4C4x8ScKFmthniEBsOg1N8-sehdZpAwEzduepArBjb1ZxCYcu7z7HbFiTw-GEWimddJIvCreTF7cGZYZlUAxcnxIRliSJydfSOUH_jzSFcf-7DneUFJitC6zwqrEKnevN8yO9K496CifiIzlA5JhnJ3m4USaVdacfZXVCmOTb4UneUYqHMqUgDsnBJSfO6XR0BV1wV3K8Zm6TCiWniLbjxK8f3obT0cl0efHO-bl5U3GseGYFolTZDUJjhV2q2o1fBRshr_WiqQfyyVRcqrP1s3UhC6viMc4NGgtiw-RYOHehSvmkpT7nSjNBmX0Y_trKgGcGjB1q4dakN5PAr_2NyYP24T-5i_3UXHV6sKKtZIJ7UT9BpyEpfqEngsyDcDYRm-jO6xom2V_Zm-urMhy9wK1HyRgvp2Vyx7U3trQRghaw85u0lUjmLoq69rpK9xzjc08dsVYtUfiYL74B1m4DANY_fq8uV03AC7uepZufQ4M6ciCLKdQq_6Zqw8qr6u_BfUO6-W2gOw-Db86y4RT3FdbN5J33WcqMnM4mELPrT0KxDu7GOJ1PPQs8tEW5yCPkqNJAdsQhYM9SpGWyli9uYb5uLI3grwaQUD6rNxPIm95oaxKcxAZQj9dO5ohzQHGov2iyT-WioKKHu6nhEJw8mQkJZF7vYpvCljGTRRrLead4khjZ6_7g49V4q7RfA2KcMe-7kZknJB-o_HbZZnUC4XIPuEaezHY-wBxE2LPW2TbkZWyFTLFLrz7pirEdRczEW9xm-s83fY8Fh4GJo-a8qMegcMUHNtOCEgr3KvT82tShXExp7XsGswge8UM8I4FDJp_fjapxA7eePjix-GciJv9UP_TpHTHnDLQjWA9boCGcc_D60qW_vywYLB8X2cp5EnaTRKwF-QUysoyHhlJgiau-3cCw7A9pLQ2BHe475aasTVh2oFvpvGOlCoKpfQoYcl791Zi9OHmShI071LbjYYFTME_9hW5kRhJAwSorOqjzAdcCNEFs5fLN8IO7r2vYP04Gc2Cu1a3iiyDPzEo3mu3ooPyV9co00DEl_CSoEjdRfyZb9ex8rUGd9UiTzwTrsYm9V55PjNTa9rhrQvjfEJC37HuNP5ovrsb-4sKx-a2psH1kTahsiMVtrHYUPO1id7SJ2Sc_QFQXRuHELSXfBrzItwTyOv_wrLP9pDpmEhVRVNSxt6WZ2GDOl_O4BuHgIcI7SpXxzGVpFSl-MMsyhqi7nhM_ej8zPPn8vcPTowWc6XwqvuY-QowYAPyEMGlKBQBDLqkDdMOXSmgrhiATowCCBDw3Ms2CTxoTRfK0qzmA2ZvbrR1p2k7jYVn5qMsTqBf6AKlK5cyCizfrKJUJdJm8CxfhZ5qhParAs9tPhDKJ-1PNaHc0aW4fVG8eVHGq49DiqkbhFoLHXIx0cW2MayIwF5JF52FSWoB0NudFp9pl_L7rd0sMyqsIEta8j8RkXF7tvRjCC8Nbh8hQ8BkX5aQAKo7vY51p1JkEL5Ig8Wp4l_NPeo4YqOhJ3MBpUhPw6SW-B2IapEMRpaSqtkPhOsfXLKHDT2_uJYCNBPtT8sg62yVf4CtQJbtcpWs5CKasgKxFOu7Hgsv_7aJvyJ__eoEDrHKO_4Rs0pW5b-xiXTw15lo2OAKqpEdDdiYC6Yy5-d_sM8vCtk-Z4zfk2zH2yHw5LsEIwbhDFreyrxT1HWp-bffR1iqO70Z6SDP8nk7WjVYEhKlUqHEgiSoCtlthV9Vh_MdHU-4dk18DRwY_jtVHlRiwChHxHmLPS89PsLTJoyum9SD45u0nq7Lj-dZ2eOQQU8qPO99S82W8xBAgVC4Lv7a-6vXgxr4ctGGT7wOd-85H4K-Z9VoCTG6U4OJxLCMx-Kc6UwGni_jbLXfbmmjV5YXlDBSy4IL8HXxGjXc1JV7pDA2OSuHFG92UJwOywUB_BPEnWEedqIELxlLOmVPlvbbNX8LPFHee8-m4t0_ANXjM2E3UeF_AD_p3j6nPPbEMG_iWoCnZG-m0O-ut0OOwzC8wE3ivrdfr2vluTT8szcnC38cypPuukaS5aoS90OIUCZNjOtenSX4_ubSR7VJf_0A8gxdcD10B1fASasvhQLjEfLBAnRehEgdEuJTYMnB3q123DXcgi4iIk5TXPjmtz_Jzgs0Y0ZNefeVUQ72W_PKIQLgkmkT7orHRkYITeTxGZTYzn_eoVvdGIKQEb3IcMQNJdcBra1-DbhEQuhHwrCUe5LV23HK0Fulled2kZDPebYxSl5EgUQ-9bv3KA13SVjMjahSCKfkRr9Z3UyxOpVC2XrNboMp5fszoYYrDf3SblNkQ4EHsWfW-rRMoUQGR8TTBVjX2bpL7njGLIa8-pkvhHkAalwqjAEn4Q_vEvFbpqrU07w-8sKG_HjhUnIw38JSu680etLchTQlz1OG_I_MTRiTssEVgiEducFrAs3CcBDKTe3Y_leeebzf-ipheMmuVt61rx6zOZIPE7i7gE_L2EITTR7L5-AvtUZsb7zkjt2794C2-_8oIWwQT4UAgBCEcbVxry1U6Bs6v7AATz1SjafHT0SEKCIUEAOPUnaJoyPvGvJdwVc1Rwfe05ae_MohLX_Qfj4zpeSvAGR9E-CmoAdsHJMV8Etwu-6iSxk1BjBiKi_jnIPcOEn16eSw-388MhbGIfv6Ukh1Yc2gS3R7Vq0AVBQxPhcLTJyV8hBKE2b0CYytx7IkxGnXZur-AEg8rMlqDtdr9xQjrl3-JdM6kYDBnBT3d56cPKxDm3cE-S_Jl-x6IpbSqSce92rTpqLZP6avSV7hdpMUC6umvTKbkfFmWhoEWSdvIwM2UOx5sPoabHCOtQA3vWGakZQ3ew32ygAxNuwdq74JfJ2btc3TYimMjAnhkghx6W6so0oxovN-PF1mRDgHljdVBaMb0pGUIbxJsh5GjdwZcfEESbq8TmuY8AaaOKNgT1F6xwKr12ILFC6OawCmjUgXJvBupvS307g5vyo7wDtVj6RXK6LiEEEVcfdtiL6-yDLLc8RIPDiVG8WTlGybU33e7GyWDlaylS6238AvuDnYqprxx-xyusbppHTn28qlsULkurjKFBPBI2sz5IMkNVncGmuJiB3f2uECuijV08jTA0GW_fWY10fbhj7s6_6AbUEEc0TUsQ1hpb6VodU379KzhT3hhU65B-m_sAX7r-uCt7EUtZId04lU7pxmV_z2NUCclzgImVNEhHrqlhzYptWwqVFHT92_QWyK_Cshqj6HpqVhO6qBLN88D0F0BxGeeGLF5gs1z4WZzzDf5OCnX7_PCjgsuwcPws2zF4sL59r1mRnt0cTpNfzGs_J0lUB0fg5DgI205fYkMgDfKCD9zwILtwK-ZW6wdxsYjYinci2Ukq0ja3n9lEM3DVaGQg5h4XWxIW9XrDNO8mlgRxOT74bAIJXlAb9KVz---jLc1pAbR0svt3Ew9dnh48z0_m7cal-_kQJ0YH4Cgi-rSRdEVkamOyrxx7Czw2-tHI6ZlkfSYD7yPslgEG6ZKM3ydHZF2E4g5rYTAVuZESEiu5BeXzlPrGM3hrDhFaX0mBopJsNnfZbXj53Qy0gAoUOuveWKdTRzqM6a9u4EyW9GJjeBGdWx8nnhLDlfdyVZnwUFB4YdUcs5cls_Jze-cq7wgsYLxXk5IP8K3-IZwW2ANJzk1laEM2utnR9VJ5wmZyHf0ICj2TtMQAl1ltGaCm4UxGhyYZWBxFKub-wVY0x414J-ZoLrXdQBsn38D9UZiAIQ5KgoniU3hUyqRuUG_3c7gmM_nm7Ft21p3XeD35AnYB9Ca94jnaGhdDtJjIwWaL_k_SdQTaRCXpsp4E1ZkPLEwPPwVhnQnk0EiFJptChMUjmmhsemmGnNfNnb_qqG5ocuCDwQP8fsdLk9qhxcDLr-ZLQJHzM1noacAmu7cYVCRUC43dokZ_cEVdsW-7so9oBdyENqYwM7u7D_akqMCBAxxhTOqY3i4R8jEGW7vy83AoRmI9dmfGMSmpvqD1GN8_N9cJEo4uMvyeKWkPzsdcGgfoTP1jwAM7gWmF9W63UwPpJKTfF8snd7--tvNgIxlNY0CcHByOuzo6TEJCwXPtoeTLqFm_kJ1Xoknghzv9P-jSf_DxPHooJcyfI8Om80mX_oe597YNvrgR6rr4TfLGHcmCk0AnwG-Qt9dh2MKfwPjjPQQ4OefOJuKnLvb4vJr07CQTN7C7uMyQwJ07UkU1gsAXYwLePH7WpyhMZvbNHGhuK3sDWNwinHXJkxli9U8D763-zOa31jJIT4X7PdkCFxmbfZ9RrzYW93RY_806HUAjiw2tjH5FWYG37zck9i-p6-EOzJ8nSQuWKEImZvV9rWHqNztCX2ahl9TEMyoqgnvyDkVfrnb0CvZ_2dfV1woeZnv80Mekqz7g9RkgV9nM8gkwgOr7nyxBBRcDmqiGsUVjlc2e8IYQqFvSz-2i4DbIce32QvmJEJDzg2Wup9UMn3lwoPUOR6t1Xko8vdVzPFs9FGb0eHAsDhonPaLvX9hX54vHkrkTr2sOax4kkkC9EPk5SAPDoYij_ioRnjx-U7qy6eGWZ6vIE8OBEZ9ClFvtcPlSQYF_xus4u4Iea54Yv-bd2PIDq_lQN-30pIJX9l1t-F_kgDyvdFffllXucdpETvqM97KJ4w4MfCcBH2SZySIaFAZFb0-E7M0uq66fsuFYCLBKxxC-m3NVC7wpASkAb2h3PPwEN7J-Hvp0aTfo6SrowC2HOQ8s8njrQ5hP2pD18oE22geRK7vHZ5QBY5nHoH8_atTHrh8nslgtmCMP9jvlREcTtMgGlvZ7yjGzqosrtyPCC8vissSn8jrZSps8im7myXnqvRYEfAVQmm37E8fJe6ZFFDPcA-TByQK2bQsX9mf0MecEQhdUdFAfm-SjF2qllYVdoxX_36ONq0zRCUkS5UkSRTSRB5kpFC-vpD0l5RpSKBMLnly0zCqi_wHayPxYCpZcDpNNpKr8yOJ9xJNeye55EEQJ6WVqNc_GBf2zk0Ujagnxi1UNv5wDEoUhtjy6b2jDxfg9mkA2aGTAHKyE_flvDvbBIhqifvIZTVXLWxJBuqZyn5i-DK5-o92dpFY_9BcISRaHvjrcmDZY1NX-jUyNA6hUmANQo-MO7YouTpf4lfefLm1qOYvJbfGY3u_S9SuoYwgEuekdKTu6myQI3jg9aVeqa1AcMmD1KUlQ3-SLyBteSUsA6Gme6Jm1-uAHmu2T5xS7iNgeuX5DM0E4CIPJfd5zxMAuxQtOo8eknP2ZYmKeHsxI4ngm5O5xJ8QW4tKj7Ca6245fsrXR-HbQh0oUWPV5Cl2hjcV7e3xz9Q_ftie2NiCgbUI9pcEK1nRbtlXER_qB-zYCmB1efkfA5YLc4XQzvxF7wAGgwA9f0UtGC0NaE8Egbuzc9WvGJYM_r084_S1YpF_SarDnYeIXA5aeFTTQUuot4_xMXCGrevAVOt3faN1d2bRHRjsjQJvPbtfOAOUq9YbWWYLnbLBIvmq3Uw-56jKzyJG4-RDlEiiVcOOqHXBW7xiVYAJ8shl59Rupl00E2zSlpWl1aoN-Pba8AyogiuM8Pnqvn06isn8yn34AwC-jxgyeoW512_gdtVjs_2dwBwS64sTQAHJOEFaZWWqMinchDoNThX71sDqGJ-7Vkfu067bYPJSmqZIsVDlXk5Oekxs8240lZLyzRx8Pg2cokFcu3yDGGRr3t1viSYDnwKmJCuInWt0A2HibC_pTbMQJ2D9wAbU9PBvD7EmowcHCmc75YS29ldgQxvKiAZlEpROJ4g5NqV90y3vUNurzF8bElK59L0pK0wFZmzBS2ap0lxfev1EjNxfpK-cN3Yvnv0QTRlNmV3LUI3gJsM9B_r7P55cLP7r_BUSB8U-yKv2hczW3zKQUEbtMcFKFtEFkXJNadWMO1bUO4phlDlGo1ZuWOS9uAm55-3HwWVkiHycAktoHeH1xbiSikwzhG2njTgxeXXMJ-0bB91oMleztdgu4snSwxtcDxTAcvAfMYKE6LKrMcNGe9yVF2JzXJEGF2lSgmwSpQ922vcm3FD1rKFKn7Ap5pJJtcLNzs5bYJiu08zMJI2XZNo_uuigeRWdSIwGGaLBlTUU6S9CCTsNVVrCT41NB7L4-5vb_UJmhvrgP0i2refF_VZs3Yb8aBkJZqyPcYz86aDncvgn6rZvOPAdNmGxMdHvgreg0mGfvQ4fI7FklVp07sEHL1rUiikm4b5wO1kxAjGCS8DZWvS1_4smiT4n37zHBBhQvNyYAFoeBQB6SPofp_1qDT0OZd4uuMpAtDtFdxLMNkYp7EPX9FQUgovnD_JsdoaRnnP2zVUyzDCi5bptZSLFtrrI0UrBbxxRai8EY4gjQMg5POsnH6cUFloXFitqjgD2DSIaVuYXWUjPrcY37vscJdNRHwoWUC4e8TgJOyFjK0q7u_C-8TDtVGFn7kmEPJ2uqaB1QGIPer9nxOhp81uagWRqAjjh4-ZJW5vKYz_57YbenQ_XVEca30swnuH0wARImMed8QpxNWzVPmsKYwSltL_DDxxJMY96N39rHOVL0sUbmkFrU1Wq2Z3ENKs2H4Nr4KhEf2aklBG1HFcNpRXlDVW8lZfjHlAPl6tD7vBYV_-_uolMC1V28XM5ecU8kPQihmMoykw2r0YvNQOpOTl2MEau96WDtegg9lj5DK0NDmsW7hcc3Qsp7LqwZZF2O03LFQlr9wh7huwCm_6edKzMQTIzG7GRvCTdbZgognBY07qjcJ3JDyZCDTMGwY9FarEigFMK8yA5ehOr1W0tzK3Sdm9Eq8B-1O0O1ZV8aUSW_OwXjYmLjWNowTUtSpKmcF4etWe3Zc38mX5F5uQgN7eJbCUkiGuWHxaXZVP_OLdDly-MIz7-ysacJAUKK1LjkFVeYkkigEcN8SWAbhf5qOi4kYbEGkgbrci8Y6dxxYO4raW1j2_MdBwzl24m4nYjTc8vbUbbn9g3ZonGJhWGPv1Ou-MHyVv9JtrUfOJ0ySh3zFPNSWSS3yc7O2z14xbGzraK-eFbuQkHOD0IECgb6YKujRY3YPGbZjk_-PwsdKSWgHchAEXLCyfVk9U9F68iHmvR2dIogot2ijdu1gOJAFHrq805ucz4MJ4yhRAFjz95a6lJzia2SdLhvdo-LcNI5C_WNiF2zllzgAgUHBICIXdpRyfxc3geGx_M1182jXbDvLyjF7oT9HXzgXSDcQdfxQst6OQnJcpd8ro_cbmgZxEFFSlhqOMPVgJRLwTEgHONPtPKzupMtSfkfl_z7Ruxvz5jbco7Wr4rnwr_imI0ECLi9L0TcJSeFa8_QT0pYOflBNamYL39orOcdNIIv46cMPIcQZ6TR8VBUfi7IdJPtbrL9Pltb8q43ka43Tiqq6-9qWTlTqF2v9wtHmmjs7OCTu8LGKXFP8eVVsVMBmvSZi6V0_VfcptxxLYTkdsEUzkgudaWYNIYg7Va3GtkoyjNkWeG9bmDTatkwT3tU5d_WbmlLvvmhStLZpLBNc0Ifhjm2MKa69mzisst8KXmI-6adMobq0lTz9U9T0PukNph_a-dy-a2k7ZzTdGonMA69L0AO6YuLvUnAmBhDL8txA14JlX8V_9ODYkdQ71iVzcMtEXCEoFhO7Egu276U4SUP2742Sg3wr1bcUjF-fSNK6Rg7KSeuj0nBMvkiq54_zxrP2Y30xt7NXCNPUlN1-YrLbaKzt0C_jbiVmx5soAGkuoKF9Va6WY9gB1qLPA99QzqjVwvrBb6toIht7Hnb1sAPYeU_4pqLykL88G_4ZP2g_K75TryYTjkNssExqnZM-7JQWCE6pQhSrq571J4vm2fK2v7XOBRxKkjwhZGeJVIqUMxq0Rxa-erArr4MCav0uda9szSD8ymNzr1jOOqBTKvskcs7wLt_KUrf2hHAn4GXMmiE9kG8B99aamt05bs4tgdy1TeKwTdOHoRPHH3Vyof88j367vPYlXfiZinLlcikVGYN_dddTqVhZmiBE_D6bLkGSxBBr1d0r7OPyCK4p9gTv7lv4YkBwfOis4lzvqhNoU-whNL80MLaFBasxxpR58TpiUFLwo7vegq65pb4-p1i5679Qul6G5d0LYk0NwRZLbpyGGOWeqbQtjT8Q-JDxyUX-dQfs2XYnHgYO65M9yevhzRaGDBrqqrVqKAPAJKF8FDlEaJjTr-H0Lld72zVCUKoG03d3_pXe2xL7SF4cL28ut92fETgToDorJZp8pDY9Nba1RLlbAgsVqubveYqXiYoiwX9U41uGfmsig2Buu68iZP_HWE6d7zICdwPjfjN0CnJ40JcjGnhumSZaa0aNHqaurbNuD0ejnRTNUqfxwlkSCRUsN9VRtT6SPxCKmBL6bdW5gn6NE6yk3iZeRIn77dEToYWI5bE_169IwnU7StCspeDtMh0tDbAUBzrIjc2ruuNdcKsybqoQILugsIhu8XLt-T4uj2fi9vMkvOd9APcyoqPTHRMZ9ZKo")},
   protobuf.Field{Number: 26, Type: 0, Value: protobuf.Varint(0)},
   protobuf.Field{Number: 29, Type: 0, Value: protobuf.Varint(0)},
   protobuf.Field{Number: 30, Type: 0, Value: protobuf.Varint(0)},
   protobuf.Field{Number: 31, Type: 0, Value: protobuf.Varint(0)},
}
